### ISSUE TITLE
could not find ais_moving from  3.1 Training set exploration.ipynb

### ISSUE THREAD

**Issue by garimss** [hakola/marine-traffic-modelling#1]
Hi,

Can you please confirm me which dataset you have used in 3.1 Training set exploration.ipynb as ais_moving. you are using training set as ais, but what is ais_moving?

Looking forward to hear from you!

Thank you
Best Regards
Garima Agrawal

**Comment by hakola** [comment]
Hi,

Thanks for your question. Yes, that might be a bit confusing without the context of the master's thesis. In my thesis work, the training set was filtered to only contain observations with speed greater than 0.1 knots. In addition, the models provided in this repository are calculated with the processed training set. I should add this info to the readme and relevant notebooks. 

The full details of the data processing used in the thesis can be found [here under 4.3 Data Preparation](https://urn.fi/URN:NBN:fi:tuni-202003262892).

**Comment by garimss** [comment]
Thanks for sharing the Thesis and explanation about it!
