### ISSUE TITLE
zip files in data folder

### ISSUE THREAD

**Issue by sadmad** [hakola/marine-traffic-modelling#3]
I tried to use the project but unfortunately the zip files in the data folder are faulty. Is it possible for you to share the data with me? 
Over all is it possible to have also the raw data?

**Comment by sadmad** [comment]
I wanted to email you, but I did not find your contact. Can you please enlighten me about how I can find AIS data? I read your paper and it was so interesting. That is how I find the repo. I worked on explosives in baltic see for the Daimon (http://www.daimonproject.com/) project and now I want to develop my data on AIS, and I need to find some raw datasets.
I'm really desperate to find anything!

**Comment by hakola** [comment]
If the files are empty, most likely you need to install git lfs before cloning the repo.  You can also find the data in IEEE Dataport (see [this link](https://ieee-dataport.org/open-access/vessel-tracking-ais-vessel-metadata-and-dirway-datasets)).

**Comment by sadmad** [comment]
The file is not empty. The zip files are broken.

**Comment by sadmad** [comment]
Thank you so much for the reply and the  link I already downloaded that file.
